name: Destroy Ordely Infrastructure

on:
  workflow_dispatch: # Manual trigger 

jobs:
  create:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
      
      - name: Mask AWS Account ID
        run: echo "::add-mask::${{ secrets.AWS_ACCOUNT_ID }}"

      - name: Creating EKS & other infrastructure with Terraform
        run: |
          echo "Creating  EKS & other infrastructure with Terraform..."
          cd terraform/prod
          terraform init
          terraform plan -var-file="terraform.tfvars"
          terraform destroy -auto-approve 

             